version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: spotify
    restart: always
    env_file:
      - .development.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  api:
    build:
      context: ./Spotify
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./csv_files:/Spotify/csv_files
    depends_on:
      - postgres

  web:
    build:
      context: ./DLP-frontend
      dockerfile: Dockerfile
    ports:
      - 5044:5044
